---
name: Data-ID-Exim
version: 0.005
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: generate Exim message IDs
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  Time::HiRes: 1.00
  base: 0
  integer: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  Data::ID::Exim:
    file: lib/Data/ID/Exim.pm
    version: 0.005
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
